spin_manifest_version = "1"
authors = ["Pachler, Uwe <uwe.pachler@datagroup.de>"]
description = ""
name = "amtsschimmel"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "amtsschimmel-import"
source = "target/wasm32-wasi/release/amtsschimmel_import.wasm"
allowed_http_hosts = ["warten.stuttgart.de"]
[component.trigger]
route = "/import"
[component.build]
command = "cargo build -p amtsschimmel-import --target wasm32-wasi --release"

[[component]]
id = "amtsschimmel-get"
source = "target/wasm32-wasi/release/amtsschimmel_get.wasm"
allowed_http_hosts = []
[component.trigger]
route = "/get"
[component.build]
command = "cargo build -p amtsschimmel-get --target wasm32-wasi --release"
workdir = "amtsschimmel-get"

[[component]]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.1/spin_static_fs.wasm", digest = "sha256:650376c33a0756b1a52cad7ca670f1126391b79050df0321407da9c741d32375" }
id = "amtsschimmel-fe"
files = [ { source = "assets", destination = "/" } ]
[component.trigger]
route = "/..."
