spin_manifest_version = "1"
authors = ["Pachler, Uwe <uwe.pachler@datagroup.de>"]
description = ""
name = "amtsschimmel"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "amtsschimmel"
source = "target/wasm32-wasi/release/amtsschimmel.wasm"
allowed_http_hosts = []
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"

[[component]]
id = "amtsschimmel-get"
source = "amtsschimmel-get/target/wasm32-wasi/release/amtsschimmel_get.wasm"
allowed_http_hosts = []
[component.trigger]
route = "/amtsschimmel-get"
[component.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "amtsschimmel-get"
